# Generated by Django 6.0.3 on 2026-04-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='edad',
            new_name='edad_anios',
        ),
        migrations.AddField(
            model_name='mascota',
            name='edad_dias',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mascota',
            name='edad_meses',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
