# Generated by Django 5.2.13 on 2026-04-16 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_rename_edad_mascota_edad_anios_mascota_edad_dias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
