# Generated by Django 5.2.13 on 2026-04-16 02:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_alter_mascota_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='codigo',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
