# Generated by Django 5.2.13 on 2026-04-16 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0005_alter_mascota_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
